### ISSUE TITLE
Crashes: abort() was called at PC 0x4014b8db on core 1

### ISSUE THREAD

**Issue by probonopd** [hitokuno/ESP32-SensorTag#1]
Getting `abort() was called at PC 0x4014b8db on core 1`:

```
load:0x40078000,len:0
load:0x40078000,len:13076
entry 0x40078a58
Starting Arduino BLE Client application...
BLE Advertised Device found: Name: , Address: 68:3b:49:bc:49:32, manufacturer data: 4c0010050b104e062f
BLE Advertised Device found: Name: CC2650 SensorTag, Address: 24:71:89:xx:xx:xx, manufacturer data: 0d00030000, serviceUUID: 0000aa80-0000-1000-8000-00805f9b34fb
Found our device!  address: 24:71:89:xx:xx:xx  RSSI: -58
E (43045) BT: btc_search_callback  BLE observe complete. Num Resp 2

Forming a connection to 24:71:89:xx:xx:xx
 - Created client
E (43047) BT: btc_gattc_call_handler()
 - Connected to server
 - Found our service
 - Found our characteristic
 - Enabled accelerometer: 111111
 - Accelerometer priod: 100*10ms
abort() was called at PC 0x4014b8db on core 1

Backtrace: 0x4008a844:0x3ffd3450 0x4008a943:0x3ffd3470 0x4014b8db:0x3ffd3490 0x4014b922:0x3ffd34b0 0x401393bf:0x3ffd34d0 0x400d6131:0x3ffd34f0 0x400d3207:0x3ffd3550 0x400d3472:0x3ffd35a0 0x4015396e:0x3ffd3600

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13076
entry 0x40078a58
Starting Arduino BLE Client application...
BLE Advertised Device found: Name: CC2650 SensorTag, Address: 24:71:89:xx:xx:xx, manufacturer data: 0d00030000, serviceUUID: 0000aa80-0000-1000-8000-00805f9b34fb
Found our device!  address: 24:71:89:xx:xx:xx  RSSI: -58
E (43035) BT: btc_search_callback  BLE observe complete. Num Resp 1

Forming a connection to 24:71:89:xx:xx:xx
 - Created client
E (43037) BT: btc_gattc_call_handler()
 - Connected to server
 - Found our service
 - Found our characteristic
 - Enabled accelerometer: 111111
 - Accelerometer priod: 100*10ms
abort() was called at PC 0x4014b8db on core 1

Backtrace: 0x4008a844:0x3ffd3450 0x4008a943:0x3ffd3470 0x4014b8db:0x3ffd3490 0x4014b922:0x3ffd34b0 0x401393bf:0x3ffd34d0 0x400d6131:0x3ffd34f0 0x400d3207:0x3ffd3550 0x400d3472:0x3ffd35a0 0x4015396e:0x3ffd3600

Rebooting...
ets Jun  8 2016 00:22:57
```

ESP32 installed today as described in https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/debian_ubuntu.md

**Comment by probonopd** [comment]
Tried with two different models of ESP32 boards.

**Comment by hitokuno** [comment]
The root cause is the latest arduino-esp32, the solution at this time is to revert back to 70d0d46.

Open a Git Bash session pointing to ARDUINO_SKETCHBOOK_DIR and execute 
$ git checkout 70d0d46
$ git submodule update --init --recursive

Open [ARDUINO_SKETCHBOOK_DIR]/hardware/espressif/esp32/tools and double-click get.exe

**Comment by hitokuno** [comment]
Please refer https://github.com/espressif/arduino-esp32/issues/1025.

**Comment by probonopd** [comment]
Thanks, I can confirm that with this it works and does not crash.

**Comment by yldzmuhammed** [comment]
Hello. I am having the same problem. Here is my log:

> Found our device!  address: Forming a connection to c3:f5:fe:bd:f3:c5
>  - Created client
>  - Connected to server
>  - Found our service
> abort() was called at PC 0x40180e4b on core 1
> 
> Backtrace: 0x40090bb4:0x3ffd5bc0 0x40090db7:0x3ffd5be0 0x40180e4b:0x3ffd5c00 0x40180e92:0x3ffd5c20 0x4016e92b:0x3ffd5c40 0x400d4521:0x3ffd5c60 0x400d171e:0x3ffd5cc0 0x400d18d1:0x3ffd5d10 0x40188a08:0x3ffd5d60
> 
> Rebooting...
> ets Jun  8 2016 00:22:57
> 
> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:1
> load:0x3fff0018,len:4
> load:0x3fff001c,len:808
> load:0x40078000,len:6084
> load:0x40080000,len:6696
> entry 0x400802e4
> Starting Arduino BLE Client application...

I did @hitokuno 's answer:

> The root cause is the latest arduino-esp32, the solution at this time is to revert back to 70d0d46.
> 
> Open a Git Bash session pointing to ARDUINO_SKETCHBOOK_DIR and execute
> $ git checkout 70d0d46
> $ git submodule update --init --recursive
> 
> Open [ARDUINO_SKETCHBOOK_DIR]/hardware/espressif/esp32/tools and double-click get.exe

But it did not work for me. What should i do? This happens when my device connect to the ble server.
